title: Travelin' On
description: A place to post updates along our journey.

url: https://blog.itsallonesong.com/
pics_url: http://www.itsallonesong.com/pics/blog/
samples_url:  http://www.itsallonesong.com/pics/samples/
jobs_url: https://www.itsallonesong.com/jobs/

incremental: true

exclude: [node_modules, create-pics, README.md]

keep_files: [assets/images, assets/media]

collections_dir: all_collections

collections:
  authors:
    output: true
  tags:
    output: true
  notes:
    output: true
    order:
      - cplusplus.md
      - bazel.md
      - conan.md
      - docker.md
      - nix.md
      - python.md
      - wsl.md
      - ubuntu.md
  personal:
    output: true
    order:
      - resume.md
      - projects.md
  private:
    output: true
    order:
      - plan.md
      - action.md

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: tags
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"
      
prose:
  rooturl: '_posts'
  siteurl: 'https://blog.itsallonesong.com/'
  media: 'assets/media'
  ignore:
    - index.html
    - _config.yml
    - _layouts
    - _includes
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "multiselect"
          label: "Add Authors"
          placeholder: "Choose Authors"
          value: "steve"
          options:
            - name: "Camilla"
              value: "camilla"
            - name: "Linda"
              value: "linda"
            - name: "Steve"
              value: "steve"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          value: "vacation"
          options:
            - name: "2021"
              value: "\"2021\""
            - name: "Beach"
              value: "beach"
            - name: "Driving"
              value: "driving"
            - name: "Food"
              value: "food"
            - name: "Hiking"
              value: "hiking"
            - name: "Summer"
              value: "summer"
            - name: "Train"
              value: "train"
            - name: "Vacation"
              value: "vacation"
            - name: "Vet"
              value: "vet"
            - name: "Video"
              value: "video"
            - name: "Camilla"
              value: "camilla"

