title: Travelin' On
description: A place to post some updates during our summer trip across the country.

url: https://blog.itsallonesong.com/

markdown: kramdown

collections:
  authors:
    output: true
  tags:
    output: true
    permalink: tag/:title/

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: tags
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"
